### ISSUE TITLE
Secret methods aren't really executed

### ISSUE THREAD

**Issue by RussellDash332** [RussellDash332/runebot#1]
The secret functions have been put inside the repository secret and when executed by the `exec()` function, there is no error. However, it cannot be called by the user.

Example:
Let `FOO = "def f(x):\n\treturn x+1"` be a repository secret which is equivalent to
```python
def f(x):
    return x+1
```
in Python. By running `exec(os.environ['FOO'])`, the user still cannot use the function `f` as there is a `NameError`.

**Comment by RussellDash332** [comment]
Current alternative is using DontPad and put everything there, but not sure with the safety.

**Comment by kevinwu328** [comment]
If there is a `NameError` when the function f is used then it might not be in the `os.environ` mapping. According to the documentation,

> os.environ
A mapping object representing the string environment. For example, environ['HOME'] is the pathname of your home directory (on some platforms), and is equivalent to getenv("HOME") in C. <br > <br >This mapping is captured the first time the os module is imported, typically during Python startup as part of processing site.py. Changes to the environment made after this time are not reflected in os.environ, except for changes made by modifying os.environ directly.

[os documentation](https://docs.python.org/3/library/os.html)

**Comment by RussellDash332** [comment]
> If there is a `NameError` when the function f is used then it might not be in the `os.environ` mapping.

For now, the workaround is setting the repo secrets inside [here](https://github.com/RussellDash332/runebot/blob/main/.github/workflows/main.yml). This means they processed the bot token and the delimiter successfully since the bot is working (first lines of [this code](https://github.com/RussellDash332/runebot/blob/main/V2/runebot.py), but not the commented ones [here](https://github.com/RussellDash332/runebot/blob/main/V2/runes.py)).

I am actually suspicious that I'm not using the `exec` function properly.

**Comment by RussellDash332** [comment]
For now DontPad solves this issue, I'm closing it.
